### ISSUE TITLE
一群走资派，劳保

### ISSUE THREAD

**Issue by singer01** [MrZhang365/HC-Plus#1]
打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！打倒MelonCmd走资派！

**Comment by MrZhang365** [comment]
这位同志，有话好好说，请不要刷屏。
首先，我是MrZhang365，不是MelonCmd，有事请直接找他，而不是在我的仓库上提出与代码无关的issue，对我进行骚扰。
感谢您的理解与支持。

**Comment by singer01** [comment]
> 这位同志，有话好好说，请不要刷屏。 首先，我是MrZhang365，不是MelonCmd，有事请直接找他，而不是在我的仓库上提出与代码无关的issue，对我进行骚扰。 感谢您的理解与支持。

他们都把我block了，请让我进入lounge

**Comment by singer01** [comment]
> 还有，我非常不建议您在我这里搞“互联网虚拟国”等幼稚行为

搞虚拟国的不应该是他们吗？

**Comment by MrZhang365** [comment]
> > 这位同志，有话好好说，请不要刷屏。 首先，我是MrZhang365，不是MelonCmd，有事请直接找他，而不是在我的仓库上提出与代码无关的issue，对我进行骚扰。 感谢您的理解与支持。
> 
> 他们都把我block了，请让我进入lounge

但是，lounge不归我管，我管理的是ZhangChat，你在这里提出issue没有任何积极作用

**Comment by MrZhang365** [comment]
而且我也不是lounge用户

**Comment by singer01** [comment]
> > > 这位同志，有话好好说，请不要刷屏。 首先，我是MrZhang365，不是MelonCmd，有事请直接找他，而不是在我的仓库上提出与代码无关的issue，对我进行骚扰。 感谢您的理解与支持。
> > 
> > 
> > 他们都把我block了，请让我进入lounge
> 
> 但是，lounge不归我管，我管理的是ZhangChat，你在这里提出issue没有任何积极作用

那为什么那个hach.chat++里面有你

**Comment by MrZhang365** [comment]
> > 还有，我非常不建议您在我这里搞“互联网虚拟国”等幼稚行为
> 
> 搞虚拟国的不应该是他们吗？

我不管，我没看到他们，他们也没对我搞

**Comment by MrZhang365** [comment]
> > > > 这位同志，有话好好说，请不要刷屏。 首先，我是MrZhang365，不是MelonCmd，有事请直接找他，而不是在我的仓库上提出与代码无关的issue，对我进行骚扰。 感谢您的理解与支持。
> > > 
> > > 
> > > 他们都把我block了，请让我进入lounge
> > 
> > 
> > 但是，lounge不归我管，我管理的是ZhangChat，你在这里提出issue没有任何积极作用
> 
> 那为什么那个hach.chat++里面有你

我只是提供了一点代码支持，并不代表我是lounge那边的

**Comment by singer01** [comment]
> > > > > 这位同志，有话好好说，请不要刷屏。 首先，我是MrZhang365，不是MelonCmd，有事请直接找他，而不是在我的仓库上提出与代码无关的issue，对我进行骚扰。 感谢您的理解与支持。
> > > > 
> > > > 
> > > > 他们都把我block了，请让我进入lounge
> > > 
> > > 
> > > 但是，lounge不归我管，我管理的是ZhangChat，你在这里提出issue没有任何积极作用
> > 
> > 
> > 那为什么那个hach.chat++里面有你
> 
> 我只是提供了一点代码支持，并不代表我是lounge那边的

ZhangChat我也进不去。。。

**Comment by singer01** [comment]
> > > 这位同志，有话好好说，请不要刷屏。 首先，我是MrZhang365，不是MelonCmd，有事请直接找他，而不是在我的仓库上提出与代码无关的issue，对我进行骚扰。 感谢您的理解与支持。
> > 
> > 
> > 他们都把我block了，请让我进入lounge
> 
> 但是，lounge不归我管，我管理的是ZhangChat，你在这里提出issue没有任何积极作用

是不能开梯子吗

**Comment by MrZhang365** [comment]
> > > > 这位同志，有话好好说，请不要刷屏。 首先，我是MrZhang365，不是MelonCmd，有事请直接找他，而不是在我的仓库上提出与代码无关的issue，对我进行骚扰。 感谢您的理解与支持。
> > > 
> > > 
> > > 他们都把我block了，请让我进入lounge
> > 
> > 
> > 但是，lounge不归我管，我管理的是ZhangChat，你在这里提出issue没有任何积极作用
> 
> 是不能开梯子吗

确实

**Comment by MrZhang365** [comment]
以及我不希望ZhangChat被卷入此事件，所以嘛… 你懂

**Comment by singer01** [comment]
> > > > > 这位同志，有话好好说，请不要刷屏。 首先，我是MrZhang365，不是MelonCmd，有事请直接找他，而不是在我的仓库上提出与代码无关的issue，对我进行骚扰。 感谢您的理解与支持。
> > > > 
> > > > 
> > > > 他们都把我block了，请让我进入lounge
> > > 
> > > 
> > > 但是，lounge不归我管，我管理的是ZhangChat，你在这里提出issue没有任何积极作用
> > 
> > 
> > 是不能开梯子吗
> 
> 确实

好的，抱歉打扰了

**Comment by MrZhang365** [comment]
> > > > > > 这位同志，有话好好说，请不要刷屏。 首先，我是MrZhang365，不是MelonCmd，有事请直接找他，而不是在我的仓库上提出与代码无关的issue，对我进行骚扰。 感谢您的理解与支持。
> > > > > 
> > > > > 
> > > > > 他们都把我block了，请让我进入lounge
> > > > 
> > > > 
> > > > 但是，lounge不归我管，我管理的是ZhangChat，你在这里提出issue没有任何积极作用
> > > 
> > > 
> > > 是不能开梯子吗
> > 
> > 
> > 确实
> 
> 好的，抱歉打扰了

没关系
